---
- hosts: all
  become: true

  vars_files:
    - vars.yml 
  
  pre_tasks:
    - name: update the apt cache if a must
      apt:
       update_cache: yes
       cache_valid_time: 3600

  roles:
    - install
    - clone
    - rundc         