---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  vars:
    docker_users:
      - "{{ ansible_user }}"
  tasks:
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
      tags:
        - docker

    - name: Add current user to the docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      with_items: "{{ docker_users }}"
      when: ansible_user != item
      tags:
        - docker

    - name: Start Docker service
      service:
        name: docker
        state: started
      tags:
        - docker

- name: Build and run Yolo_app in Docker container
  hosts: yolo_app
  become: true
  vars:
    app_name: yolo_app
    app_tag: latest
    app_path: /path/to/yolo_app
    app_network: yolo_app_network
    app_env: dev
  tasks:
    - name: Create Docker network
      docker_network:
        name: "yolo_app_network"
      tags:
        - yolo_app

    - name: Build Yolo app Docker image
      docker_image:
        name: "my_yolo_app:v1"
        path: "Moringa/Devops/Yolo_app/"
        buildargs:
          - "APP_ENV=production"
        pull: yes
        force_tag: yes
        state: present
      tags:
        - yolo_app

    - name: Start Yolo app Docker container
      docker_container:
        name: "yolo_app_container"
        image: "yolo_app:v1.0"
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
        networks:
          - name: "yolo_app_network"
        tags:
          - yolo_app
