---
- name: Install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
  tags:
    - docker

- name: Add current user to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  when: ansible_user != item
  tags:
    - docker

- name: Start Docker service
  service:
    name: docker
    state: started
  tags:
    - docker
