apiVersion: v1
kind: Service
metadata:
  name: yolo-svc
  namespace: development
  labels:
    app: yolo-svc
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000

