---
- name: Create Docker network
  docker_network:
    name: "yolo_app_network"
  tags:
    - yolo_app

- name: Build Yolo app Docker image
  docker_image:
    name: "yolo_app:latest"
    path: "/vagrant/Yolo_app"
    buildargs:
      - "APP_ENV=dev"
    pull: yes
    force_tag: yes
    state: present
  tags:
    - yolo_app

- name: Start Yolo app Docker container
 
